config/routes.rb
Rehash::Application.routes.draw do

  resources :users

  root :to => 'recordings#login'

  get '/dashboard' => 'recordings#dashboard', :as => 'dashboard'
  post '/dashboard' => 'recordings#create', :as => 'recordings'
  get '/recordings' => 'recordings#index', :as => 'recording'
  get '/oldindex' => 'recordings#index', :as => 'oldindex'

  resources :tweetstores

  match 'auth/twitter/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
end

app/models/tweetstore.rb
class Tweetstore < ActiveRecord::Base
  attr_accessible :name, :profile_image_url, :screen_name, :text, :tweeted_at
end

app/controllers/tweetstores_controller.rb
require 'rubygems'
require 'tweetstream'

def start_stream

  TweetStream.configure do |config|
    config.consumer_key       = '5nXwpUUV7nZnhPYUnE5YA'  
    config.consumer_secret    = '8BQWOjhP9wNDsLhMRxtAobI31InkjtreGwj564s'

    # this works
    config.oauth_token        = User.first.token
    config.oauth_token_secret = User.first.secret   # shhhhhhhh

    config.auth_method        = :oauth
  end

  count = 0
  
  puts "Listening    #{Time.now}"

  client = TweetStream::Client.new

  client.on_error do |message|
    puts "Error: #{Time.now}"
    puts message
  end

  client.on_direct_message do |direct_message|
    puts Time.now
    puts "@#{direct_message.sender.screen_name} sent a direct message"
    puts direct_message.text
  end

  client.on_timeline_status do |status|
    puts Time.now
    puts "@#{status.user.screen_name} said"
    puts status.text
    Tweetstore.create  :name => status.user.name,
                       :screen_name => status.user.screen_name,
                       :text => status.text,
                       :tweeted_at => status.created_at,
                       :profile_image_url =>  status.user.profile_image_url
    count += 1
    if count > 2
      render '/recordings/dashboard_url'
      count = 0
    end
  end

puts "going into userstream"
  client.userstream
puts "back from userstream"
  
end 
  
  # Tweetstore.destroy_all
  
  
  # TweetStream::Client.new.track('obama') do |status|  

  # client = TweetStream::Client.new
  # 
  # client.sitestream([session[:uid]], :followings => true) do |status|

 #  if config.oauth_token && config.oauth_token_secret
 #     TweetStream::Client.new().sample do |status|
 #     
 #       count += 1
 #       puts count
 #       Tweetstore.create  :name => status.user.name,
 #                       :screen_name => status.user.screen_name,
 #                       :text => status.text,
 #                       :tweeted_at => status.created_at,
 #                       :profile_image_url =>  status.user.profile_image_url
 #       if count > 5
 #         break
 #       end
 #     end
 #   else
 #     puts "No token or secret"
 #   end  
 # end 
 

class TweetstoresController < ApplicationController
  # GET /tweetstores
  # GET /tweetstores.json
  def index
    start_stream
    @tweetstores = Tweetstore.all
    
    respond_to do |format|
      format.html { redirect_to dashboard_url } # index.html.erb
      format.json { render json: @tweetstores }
    end
  end

  # GET /tweetstores/1
  # GET /tweetstores/1.json
  def show
    @tweetstore = Tweetstore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweetstore }
    end
  end

  # GET /tweetstores/new
  # GET /tweetstores/new.json
  def new
    @tweetstore = Tweetstore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweetstore }
    end
  end

  # GET /tweetstores/1/edit
  def edit
    @tweetstore = Tweetstore.find(params[:id])
  end

  # POST /tweetstores
  # POST /tweetstores.json
  def create
    @tweetstore = Tweetstore.new(params[:tweetstore])

    respond_to do |format|
      if @tweetstore.save
        format.html { redirect_to @tweetstore, notice: 'Tweetstore was successfully created.' }
        format.json { render json: @tweetstore, status: :created, location: @tweetstore }
      else
        format.html { render action: "new" }
        format.json { render json: @tweetstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweetstores/1
  # PUT /tweetstores/1.json
  def update
    @tweetstore = Tweetstore.find(params[:id])

    respond_to do |format|
      if @tweetstore.update_attributes(params[:tweetstore])
        format.html { redirect_to @tweetstore, notice: 'Tweetstore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweetstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweetstores/1
  # DELETE /tweetstores/1.json
  def destroy
    @tweetstore = Tweetstore.find(params[:id])
    @tweetstore.destroy

    respond_to do |format|
      format.html { redirect_to tweetstores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tweetstores_helper.rb
module TweetstoresHelper
end

app/views/tweetstores/_form.html.erb
<%= form_for(@tweetstore) do |f| %>
  <% if @tweetstore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweetstore.errors.count, "error") %> prohibited this tweetstore from being saved:</h2>

      <ul>
      <% @tweetstore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :screen_name %><br />
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :profile_image_url %><br />
    <%= f.text_field :profile_image_url %>
  </div>
  <div class="field">
    <%= f.label :tweeted_at %><br />
    <%= f.datetime_select :tweeted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweetstores/edit.html.erb
<h1>Editing tweetstore</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweetstore %> |
<%= link_to 'Back', tweetstores_path %>

app/views/tweetstores/index.html.erb
<h1>Listing tweetstores</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Screen name</th>
    <th>Text</th>
    <th>Profile image url</th>
    <th>Tweeted at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweetstores.each do |tweetstore| %>
<tr>
    <td><%= image_tag tweetstore.profile_image_url %></td>
    <td><%= tweetstore.text %></td>
    <td><%= tweetstore.name %></td>
    <td><%= tweetstore.screen_name %></td>
    <td><%= tweetstore.tweeted_at %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Tweetstore', new_tweetstore_path %>

app/views/tweetstores/new.html.erb
<h1>New tweetstore</h1>

<%= render 'form' %>

<%= link_to 'Back', tweetstores_path %>

app/views/tweetstores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tweetstore.name %>
</p>

<p>
  <b>Screen name:</b>
  <%= @tweetstore.screen_name %>
</p>

<p>
  <b>Text:</b>
  <%= @tweetstore.text %>
</p>

<p>
  <b>Profile image url:</b>
  <%= @tweetstore.profile_image_url %>
</p>

<p>
  <b>Tweeted at:</b>
  <%= @tweetstore.tweeted_at %>
</p>


<%= link_to 'Edit', edit_tweetstore_path(@tweetstore) %> |
<%= link_to 'Back', tweetstores_path %>